name: Windows CUDA Build

on:
  push:
  pull_request:

jobs:
  build-windows-gpu:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Download CUDA Toolkit 12.2
      run: |
        curl -L -o cuda.exe https://developer.download.nvidia.com/compute/cuda/12.2.2/network_installers/cuda_12.2.2_windows_network.exe
        start /wait cuda.exe -s nvcc_12.2 cudart_12.2

    - name: Add CUDA to PATH
      shell: powershell
      run: |
        echo "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\lib\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Verify CUDA
      run: nvcc --version

    - name: Build GPU OpenSSL version
      run: |
        nvcc -std=c++11 -O3 -DUSE_CUDA -DUSE_OPENSSL gpu_hash_searcher.cpp ^
            -o hash_searcher_gpu_ssl.exe -lcudart -lssl -lcrypto

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hash_searcher-windows-gpu
        path: hash_searcher_gpu_ssl.exe
