name: Build GPU Hash Searcher

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows-gpu:
    runs-on: windows-2019
    name: Build Windows GPU Version
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1

    - name: Install CUDA Toolkit
      run: |
        # Download CUDA installer
        $url = "https://developer.download.nvidia.com/compute/cuda/12.0.0/network_installers/cuda_12.0.0_windows_network.exe"
        $output = "cuda_installer.exe"
        
        Write-Host "Downloading CUDA installer..."
        Invoke-WebRequest -Uri $url -OutFile $output
        
        Write-Host "Installing CUDA (this may take several minutes)..."
        Start-Process -Wait -FilePath $output -ArgumentList "-s nvcc_12.0 cudart_12.0 curand_dev_12.0 cublas_dev_12.0 visual_studio_integration_12.0"
        
        # Set environment variables for this session
        $cudaPath = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0"
        echo "$cudaPath\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "CUDA_PATH=$cudaPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: powershell

    - name: Setup vcpkg for OpenSSL
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '2023.11.20'

    - name: Install OpenSSL
      run: |
        vcpkg install openssl:x64-windows-static
      shell: cmd

    - name: Verify CUDA installation
      run: |
        nvcc --version
        dir "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin\"
      shell: cmd

    - name: Build Windows GPU version
      run: |
        $cudaPath = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0"
        $vcpkgPath = "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows-static"
        
        & "$cudaPath\bin\nvcc.exe" `
          -std=c++11 -O3 -DUSE_CUDA -DUSE_OPENSSL `
          -I"$vcpkgPath\include" `
          gpu_hash_searcher.cpp `
          -o hash_searcher_windows_gpu.exe `
          -lcudart `
          -L"$vcpkgPath\lib" `
          -llibssl -llibcrypto -lws2_32 -lcrypt32
      shell: powershell

    - name: Verify executable
      run: |
        dir hash_searcher_windows_gpu.exe
        hash_searcher_windows_gpu.exe --help 2>&1 || echo "Executable created successfully"
      shell: cmd

    - name: Upload Windows GPU executable
      uses: actions/upload-artifact@v4
      with:
        name: hash_searcher_windows_gpu
        path: hash_searcher_windows_gpu.exe

  # Optional: Create a combined release artifact
  package-release:
    needs: [build-linux-gpu, build-windows-gpu]
    runs-on: ubuntu-latest
    name: Package Release
    
    steps:
    - name: Download Linux executable
      uses: actions/download-artifact@v4
      with:
        name: hash_searcher_linux_gpu
        path: linux/

    - name: Download Windows executable
      uses: actions/download-artifact@v4
      with:
        name: hash_searcher_windows_gpu
        path: windows/

    - name: Create release package
      run: |
        mkdir -p release_package
        
        # Copy executables to release folder
        cp linux/hash_searcher_linux_gpu.exe release_package/
        cp windows/hash_searcher_windows_gpu.exe release_package/
        
        # Create README for the release
        cat > release_package/README.txt << 'EOF'
        GPU Hash Searcher - Release Package
        ==================================
        
        This package contains GPU-accelerated versions of the hash searcher:
        
        Files included:
        - hash_searcher_linux_gpu.exe    (Linux x64 with CUDA + OpenSSL)
        - hash_searcher_windows_gpu.exe  (Windows x64 with CUDA + OpenSSL)
        
        Requirements:
        - NVIDIA GPU with CUDA support (Compute Capability 3.0+)
        - CUDA Runtime 12.0+ installed on target system
        - For Linux: libssl and libcrypto libraries
        
        Usage:
        1. Ensure your NVIDIA drivers and CUDA runtime are installed
        2. Run the appropriate executable for your platform
        3. Follow the interactive prompts
        
        Performance:
        - GPU versions provide 50-1000x speedup over CPU versions
        - Actual performance depends on your GPU model
        
        Support:
        - Visit the project repository for documentation and issues
        EOF
        
        # List contents
        ls -la release_package/

    - name: Upload combined package
      uses: actions/upload-artifact@v4
      with:
        name: hash_searcher_gpu_release
        path: release_package/
